// Generated by scripts/gen-icons.mjs. Do not edit.
//
// Covers every icon named in app/lib/tools.ts plus every literal <Icon @name>
// in a .gts template. Re-run after adding either.

import iArrowRight from 'lucide-static/icons/arrow-right.svg?raw';
import iArrowUpDown from 'lucide-static/icons/arrow-up-down.svg?raw';
import iBarcode from 'lucide-static/icons/barcode.svg?raw';
import iBinary from 'lucide-static/icons/binary.svg?raw';
import iBlend from 'lucide-static/icons/blend.svg?raw';
import iBookOpen from 'lucide-static/icons/book-open.svg?raw';
import iBrush from 'lucide-static/icons/brush.svg?raw';
import iCalculator from 'lucide-static/icons/calculator.svg?raw';
import iCaseUpper from 'lucide-static/icons/case-upper.svg?raw';
import iCheck from 'lucide-static/icons/check.svg?raw';
import iChevronDown from 'lucide-static/icons/chevron-down.svg?raw';
import iChevronsUpDown from 'lucide-static/icons/chevrons-up-down.svg?raw';
import iCircleAlert from 'lucide-static/icons/circle-alert.svg?raw';
import iClipboardPaste from 'lucide-static/icons/clipboard-paste.svg?raw';
import iClock from 'lucide-static/icons/clock.svg?raw';
import iCombine from 'lucide-static/icons/combine.svg?raw';
import iContrast from 'lucide-static/icons/contrast.svg?raw';
import iCopy from 'lucide-static/icons/copy.svg?raw';
import iCrop from 'lucide-static/icons/crop.svg?raw';
import iCrosshair from 'lucide-static/icons/crosshair.svg?raw';
import iDownload from 'lucide-static/icons/download.svg?raw';
import iEraser from 'lucide-static/icons/eraser.svg?raw';
import iExternalLink from 'lucide-static/icons/external-link.svg?raw';
import iEye from 'lucide-static/icons/eye.svg?raw';
import iFileCode from 'lucide-static/icons/file-code.svg?raw';
import iFileImage from 'lucide-static/icons/file-image.svg?raw';
import iFileSearch from 'lucide-static/icons/file-search.svg?raw';
import iFileText from 'lucide-static/icons/file-text.svg?raw';
import iFileType from 'lucide-static/icons/file-type.svg?raw';
import iFileType2 from 'lucide-static/icons/file-type-2.svg?raw';
import iFrown from 'lucide-static/icons/frown.svg?raw';
import iGalleryVertical from 'lucide-static/icons/gallery-vertical.svg?raw';
import iGitCompare from 'lucide-static/icons/git-compare.svg?raw';
import iHash from 'lucide-static/icons/hash.svg?raw';
import iHome from 'lucide-static/icons/home.svg?raw';
import iImage from 'lucide-static/icons/image.svg?raw';
import iInfo from 'lucide-static/icons/info.svg?raw';
import iKeyRound from 'lucide-static/icons/key-round.svg?raw';
import iLanguages from 'lucide-static/icons/languages.svg?raw';
import iLayers from 'lucide-static/icons/layers.svg?raw';
import iLayoutGrid from 'lucide-static/icons/layout-grid.svg?raw';
import iLibrary from 'lucide-static/icons/library.svg?raw';
import iLineChart from 'lucide-static/icons/line-chart.svg?raw';
import iLoaderCircle from 'lucide-static/icons/loader-circle.svg?raw';
import iLock from 'lucide-static/icons/lock.svg?raw';
import iMinus from 'lucide-static/icons/minus.svg?raw';
import iMoon from 'lucide-static/icons/moon.svg?raw';
import iPalette from 'lucide-static/icons/palette.svg?raw';
import iPanelLeft from 'lucide-static/icons/panel-left.svg?raw';
import iPenLine from 'lucide-static/icons/pen-line.svg?raw';
import iPipette from 'lucide-static/icons/pipette.svg?raw';
import iPlus from 'lucide-static/icons/plus.svg?raw';
import iQrCode from 'lucide-static/icons/qr-code.svg?raw';
import iRainbow from 'lucide-static/icons/rainbow.svg?raw';
import iRefreshCw from 'lucide-static/icons/refresh-cw.svg?raw';
import iRegex from 'lucide-static/icons/regex.svg?raw';
import iRuler from 'lucide-static/icons/ruler.svg?raw';
import iScale from 'lucide-static/icons/scale.svg?raw';
import iScanLine from 'lucide-static/icons/scan-line.svg?raw';
import iScissors from 'lucide-static/icons/scissors.svg?raw';
import iSearch from 'lucide-static/icons/search.svg?raw';
import iShuffle from 'lucide-static/icons/shuffle.svg?raw';
import iSmartphone from 'lucide-static/icons/smartphone.svg?raw';
import iSparkles from 'lucide-static/icons/sparkles.svg?raw';
import iSquare from 'lucide-static/icons/square.svg?raw';
import iSquareTerminal from 'lucide-static/icons/square-terminal.svg?raw';
import iStamp from 'lucide-static/icons/stamp.svg?raw';
import iStar from 'lucide-static/icons/star.svg?raw';
import iSun from 'lucide-static/icons/sun.svg?raw';
import iTag from 'lucide-static/icons/tag.svg?raw';
import iTrash2 from 'lucide-static/icons/trash-2.svg?raw';
import iType from 'lucide-static/icons/type.svg?raw';
import iUnlock from 'lucide-static/icons/unlock.svg?raw';
import iUpload from 'lucide-static/icons/upload.svg?raw';
import iVariable from 'lucide-static/icons/variable.svg?raw';
import iWand2 from 'lucide-static/icons/wand-2.svg?raw';
import iWind from 'lucide-static/icons/wind.svg?raw';
import iX from 'lucide-static/icons/x.svg?raw';

export const icons: Record<string, string> = {
	'arrow-right': iArrowRight,
	'arrow-up-down': iArrowUpDown,
	barcode: iBarcode,
	binary: iBinary,
	blend: iBlend,
	'book-open': iBookOpen,
	brush: iBrush,
	calculator: iCalculator,
	'case-upper': iCaseUpper,
	check: iCheck,
	'chevron-down': iChevronDown,
	'chevrons-up-down': iChevronsUpDown,
	'circle-alert': iCircleAlert,
	'clipboard-paste': iClipboardPaste,
	clock: iClock,
	combine: iCombine,
	contrast: iContrast,
	copy: iCopy,
	crop: iCrop,
	crosshair: iCrosshair,
	download: iDownload,
	eraser: iEraser,
	'external-link': iExternalLink,
	eye: iEye,
	'file-code': iFileCode,
	'file-image': iFileImage,
	'file-search': iFileSearch,
	'file-text': iFileText,
	'file-type': iFileType,
	'file-type-2': iFileType2,
	frown: iFrown,
	'gallery-vertical': iGalleryVertical,
	'git-compare': iGitCompare,
	hash: iHash,
	home: iHome,
	image: iImage,
	info: iInfo,
	'key-round': iKeyRound,
	languages: iLanguages,
	layers: iLayers,
	'layout-grid': iLayoutGrid,
	library: iLibrary,
	'line-chart': iLineChart,
	'loader-circle': iLoaderCircle,
	lock: iLock,
	minus: iMinus,
	moon: iMoon,
	palette: iPalette,
	'panel-left': iPanelLeft,
	'pen-line': iPenLine,
	pipette: iPipette,
	plus: iPlus,
	'qr-code': iQrCode,
	rainbow: iRainbow,
	'refresh-cw': iRefreshCw,
	regex: iRegex,
	ruler: iRuler,
	scale: iScale,
	'scan-line': iScanLine,
	scissors: iScissors,
	search: iSearch,
	shuffle: iShuffle,
	smartphone: iSmartphone,
	sparkles: iSparkles,
	square: iSquare,
	'square-terminal': iSquareTerminal,
	stamp: iStamp,
	star: iStar,
	sun: iSun,
	tag: iTag,
	'trash-2': iTrash2,
	type: iType,
	unlock: iUnlock,
	upload: iUpload,
	variable: iVariable,
	'wand-2': iWand2,
	wind: iWind,
	x: iX,
};
