// Tool icons below are generated by scripts/port-registry.mjs from lib/tools.ts.
// The chrome block is hand-maintained: those icons are used by the sidebar and
// header, not by any registry entry, so the generator never sees them.
import iHome from 'lucide-static/icons/home.svg?raw';
import iSearch from 'lucide-static/icons/search.svg?raw';
import iX from 'lucide-static/icons/x.svg?raw';
import iStar from 'lucide-static/icons/star.svg?raw';
import iInfo from 'lucide-static/icons/info.svg?raw';
import iMoon from 'lucide-static/icons/moon.svg?raw';
import iSun from 'lucide-static/icons/sun.svg?raw';
import iFrown from 'lucide-static/icons/frown.svg?raw';
import iPanelLeft from 'lucide-static/icons/panel-left.svg?raw';
import iBarcode from 'lucide-static/icons/barcode.svg?raw';
import iBinary from 'lucide-static/icons/binary.svg?raw';
import iBlend from 'lucide-static/icons/blend.svg?raw';
import iBookOpen from 'lucide-static/icons/book-open.svg?raw';
import iBrush from 'lucide-static/icons/brush.svg?raw';
import iCalculator from 'lucide-static/icons/calculator.svg?raw';
import iCaseUpper from 'lucide-static/icons/case-upper.svg?raw';
import iClipboardPaste from 'lucide-static/icons/clipboard-paste.svg?raw';
import iClock from 'lucide-static/icons/clock.svg?raw';
import iCombine from 'lucide-static/icons/combine.svg?raw';
import iContrast from 'lucide-static/icons/contrast.svg?raw';
import iCrop from 'lucide-static/icons/crop.svg?raw';
import iCrosshair from 'lucide-static/icons/crosshair.svg?raw';
import iEraser from 'lucide-static/icons/eraser.svg?raw';
import iEye from 'lucide-static/icons/eye.svg?raw';
import iFileCode from 'lucide-static/icons/file-code.svg?raw';
import iFileImage from 'lucide-static/icons/file-image.svg?raw';
import iFileSearch from 'lucide-static/icons/file-search.svg?raw';
import iFileText from 'lucide-static/icons/file-text.svg?raw';
import iFileType from 'lucide-static/icons/file-type.svg?raw';
import iFileType2 from 'lucide-static/icons/file-type-2.svg?raw';
import iGalleryVertical from 'lucide-static/icons/gallery-vertical.svg?raw';
import iGitCompare from 'lucide-static/icons/git-compare.svg?raw';
import iHash from 'lucide-static/icons/hash.svg?raw';
import iImage from 'lucide-static/icons/image.svg?raw';
import iKeyRound from 'lucide-static/icons/key-round.svg?raw';
import iLanguages from 'lucide-static/icons/languages.svg?raw';
import iLayers from 'lucide-static/icons/layers.svg?raw';
import iLayoutGrid from 'lucide-static/icons/layout-grid.svg?raw';
import iLibrary from 'lucide-static/icons/library.svg?raw';
import iLineChart from 'lucide-static/icons/line-chart.svg?raw';
import iPalette from 'lucide-static/icons/palette.svg?raw';
import iPenLine from 'lucide-static/icons/pen-line.svg?raw';
import iPipette from 'lucide-static/icons/pipette.svg?raw';
import iQrCode from 'lucide-static/icons/qr-code.svg?raw';
import iRainbow from 'lucide-static/icons/rainbow.svg?raw';
import iRefreshCw from 'lucide-static/icons/refresh-cw.svg?raw';
import iRegex from 'lucide-static/icons/regex.svg?raw';
import iRuler from 'lucide-static/icons/ruler.svg?raw';
import iScale from 'lucide-static/icons/scale.svg?raw';
import iScanLine from 'lucide-static/icons/scan-line.svg?raw';
import iScissors from 'lucide-static/icons/scissors.svg?raw';
import iSmartphone from 'lucide-static/icons/smartphone.svg?raw';
import iSparkles from 'lucide-static/icons/sparkles.svg?raw';
import iSquare from 'lucide-static/icons/square.svg?raw';
import iSquareTerminal from 'lucide-static/icons/square-terminal.svg?raw';
import iStamp from 'lucide-static/icons/stamp.svg?raw';
import iTag from 'lucide-static/icons/tag.svg?raw';
import iType from 'lucide-static/icons/type.svg?raw';
import iVariable from 'lucide-static/icons/variable.svg?raw';
import iWind from 'lucide-static/icons/wind.svg?raw';

export const icons: Record<string, string> = {
  home: iHome,
  search: iSearch,
  x: iX,
  star: iStar,
  info: iInfo,
  moon: iMoon,
  sun: iSun,
  frown: iFrown,
  'panel-left': iPanelLeft,
  barcode: iBarcode,
  binary: iBinary,
  blend: iBlend,
  'book-open': iBookOpen,
  brush: iBrush,
  calculator: iCalculator,
  'case-upper': iCaseUpper,
  'clipboard-paste': iClipboardPaste,
  clock: iClock,
  combine: iCombine,
  contrast: iContrast,
  crop: iCrop,
  crosshair: iCrosshair,
  eraser: iEraser,
  eye: iEye,
  'file-code': iFileCode,
  'file-image': iFileImage,
  'file-search': iFileSearch,
  'file-text': iFileText,
  'file-type': iFileType,
  'file-type-2': iFileType2,
  'gallery-vertical': iGalleryVertical,
  'git-compare': iGitCompare,
  hash: iHash,
  image: iImage,
  'key-round': iKeyRound,
  languages: iLanguages,
  layers: iLayers,
  'layout-grid': iLayoutGrid,
  library: iLibrary,
  'line-chart': iLineChart,
  palette: iPalette,
  'pen-line': iPenLine,
  pipette: iPipette,
  'qr-code': iQrCode,
  rainbow: iRainbow,
  'refresh-cw': iRefreshCw,
  regex: iRegex,
  ruler: iRuler,
  scale: iScale,
  'scan-line': iScanLine,
  scissors: iScissors,
  smartphone: iSmartphone,
  sparkles: iSparkles,
  square: iSquare,
  'square-terminal': iSquareTerminal,
  stamp: iStamp,
  tag: iTag,
  type: iType,
  variable: iVariable,
  wind: iWind,
};
