// Regenerates app/lib/icons.ts from the icons actually referenced in the app.
//
// Two sources: the `icon:` field of every entry in app/lib/tools.ts, and every
// literal `<Icon @name="..." />` in a .gts file. Anything referenced through a
// variable cannot be seen here, so add those to EXTRA below.
//
// Usage: node scripts/gen-icons.mjs

import {
	readFileSync,
	writeFileSync,
	existsSync,
	readdirSync,
	statSync,
} from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const { allTools } = await import('../app/lib/tools.ts');
const { FX_ICONS, FX_ICON_FALLBACK } =
	await import('../app/lib/substrata/fx-icons.ts');

/** Referenced via a binding rather than a literal, so the scan cannot find
 *  them. The four below are returned from component getters (toast-slot's
 *  clipboard states, the module pin toggle, the layer lock toggle); the FX
 *  picker's cards read their glyph out of a type→icon map. */
const EXTRA = [
	'clipboard-x',
	'lock-open',
	'pin',
	'pin-off',
	// pdf-page-numberer's 3x3 position picker reads its glyphs from ANCHOR_ICON.
	'arrow-up-left',
	'arrow-up',
	'arrow-up-right',
	'arrow-left',
	'dot',
	'arrow-right',
	'arrow-down-left',
	'arrow-down',
	'arrow-down-right',
	...Object.values(FX_ICONS),
	FX_ICON_FALLBACK,
];

function walk(dir) {
	return readdirSync(dir).flatMap((entry) => {
		const p = join(dir, entry);
		return statSync(p).isDirectory() ? walk(p) : [p];
	});
}

const fromTemplates = new Set();
const candidates = new Set();
for (const file of walk(join(root, 'app')).filter((f) => f.endsWith('.gts'))) {
	const src = readFileSync(file, 'utf8');
	// Literal `@name="foo"`.
	for (const m of src.matchAll(/@name=["']([a-z0-9-]+)["']/g)) {
		fromTemplates.add(m[1]);
	}
	// Names chosen inside a helper, e.g. `@name={{if cond "check" "copy"}}`.
	// Every quoted string in the expression is a candidate; the ones that are
	// not lucide icons (comparison keys and the like) are dropped below.
	for (const m of src.matchAll(/@name=\{\{[^}]*\}\}/g)) {
		for (const s of m[0].matchAll(/["']([a-z0-9-]+)["']/g)) {
			candidates.add(s[1]);
		}
	}
	// Data-driven icons: `icon: 'x'` registry/option fields (the omnibar
	// tools, the module registry, align options…) and `@icon="x"` component
	// args (StepBtn). Candidates too — an `icon:` field can hold a non-lucide
	// value.
	for (const m of src.matchAll(/\bicon:\s*["']([a-z0-9-]+)["']/g)) {
		candidates.add(m[1]);
	}
	for (const m of src.matchAll(/@icon=["']([a-z0-9-]+)["']/g)) {
		candidates.add(m[1]);
	}
}

const isIcon = (n) =>
	existsSync(join(root, 'node_modules/lucide-static/icons', `${n}.svg`));

const names = [
	...new Set([
		...allTools.map((t) => t.icon),
		...fromTemplates,
		...[...candidates].filter(isIcon),
		...EXTRA,
	]),
]
	.filter(Boolean)
	.sort();

// Only names asserted directly are errors; candidates were already filtered.
const missing = names.filter((n) => !isIcon(n));
if (missing.length) {
	throw new Error(`not in lucide-static: ${missing.join(', ')}`);
}

const ident = (n) =>
	'i' +
	n
		.split('-')
		.map((w) => w[0].toUpperCase() + w.slice(1))
		.join('');

// Tabs, and quotes only on the hyphenated names — matches what prettier would
// do to this file, so `lint:format` stays green without a formatting pass.
const key = (n) => (/^[a-z][a-z\d]*$/.test(n) ? n : `'${n}'`);

const out = `// Generated by scripts/gen-icons.mjs. Do not edit.
//
// Covers every icon named in app/lib/tools.ts plus every literal <Icon @name>
// in a .gts template. Re-run after adding either.

${names.map((n) => `import ${ident(n)} from 'lucide-static/icons/${n}.svg?raw';`).join('\n')}

export const icons: Record<string, string> = {
${names.map((n) => `\t${key(n)}: ${ident(n)},`).join('\n')}
};
`;

writeFileSync(join(root, 'app/lib/icons.ts'), out);
console.log(`wrote app/lib/icons.ts — ${names.length} icons`);
