// generator cannot scan maps
export const FX_ICONS: Record<string, string> = {
	brightness: 'sun',
	contrast: 'contrast',
	exposure: 'aperture',
	saturation: 'droplet',
	vibrance: 'droplets',
	'hue-rotate': 'rainbow',
	temperature: 'thermometer',
	grayscale: 'eclipse',
	sepia: 'coffee',
	invert: 'circle-slash',
	threshold: 'binary',
	gamma: 'spline',
	posterize: 'chart-column-big',
	levels: 'sliders-horizontal',
	'colour-balance': 'scale',
	duotone: 'blend',
	'gaussian-blur': 'circle-dashed',
	sharpen: 'focus',
	emboss: 'stamp',
	'edge-detect': 'scan-line',
	noise: 'grip',
	pixelate: 'grid-3x3',
	vignette: 'circle-dot',
	'drop-shadow': 'square-stack',
	'outer-glow': 'lightbulb',
	stroke: 'square',
	'inner-shadow': 'square-square',
	'inner-glow': 'sparkle',
	'colour-overlay': 'paint-bucket',
	'remove-background': 'scissors',
};

export const FX_ICON_FALLBACK = 'plus';
